ADDIC7ED_URL = "https://www.addic7ed.com"
CONFIG_FILE_NAME = ".addic7edrc"
LANG_DEFAULT = "en"

# Language code - "ISO 639-1"
# "code" is the number used at addic7ed.com
LANG_ISO = {
    "all":      {"code": 0,     "name": "All languages", "addic7ed": True},
    "ar":       {"code": 38,    "name": "Arabic", "addic7ed": True},
    "az":       {"code": 48,    "name": "Azerbaijani", "addic7ed": True},
    "bg":       {"code": 35,    "name": "Bulgarian", "addic7ed": True},
    "bn":       {"code": 47,    "name": "Bengali", "addic7ed": True},
    "bs":       {"code": 44,    "name": "Bosnian", "addic7ed": True},
    "ca":       {"code": 12,    "name": "Català", "addic7ed": True},
    "cs":       {"code": 14,    "name": "Czech", "addic7ed": True},
    "da":       {"code": 30,    "name": "Danish", "addic7ed": True},
    "de":       {"code": 11,    "name": "German", "addic7ed": True},
    "el":       {"code": 27,    "name": "Greek", "addic7ed": True},
    "en":       {"code": 1,     "name": "English", "addic7ed": True},
    "es":       {"code": 4,     "name": "Spanish", "addic7ed": True},
    "es-la":    {"code": 6,     "name": "Spanish (Latin America)", "addic7ed": True},
    "es-es":    {"code": 5,     "name": "Spanish (Spain)", "addic7ed": True},
    "et":       {"code": 54,    "name": "Estonian", "addic7ed": True},
    "eu":       {"code": 13,    "name": "Euskera", "addic7ed": True},
    "fa":       {"code": 43,    "name": "Persian", "addic7ed": True},
    "fi":       {"code": 28,    "name": "Finnish", "addic7ed": True},
    "fr":       {"code": 8,     "name": "French", "addic7ed": True},
    "fr-ca":    {"code": 53,    "name": "French (Canadian)", "addic7ed": True},
    "gl":       {"code": 15,    "name": "Galego", "addic7ed": True},
    "he":       {"code": 23,    "name": "Hebrew", "addic7ed": True},
    "hi":       {"code": 55,    "name": "Hindi", "addic7ed": True},
    "hr":       {"code": 31,    "name": "Croatian", "addic7ed": True},
    "hu":       {"code": 20,    "name": "Hungarian", "addic7ed": True},
    "hy":       {"code": 50,    "name": "Armenian", "addic7ed": True},
    "id":       {"code": 37,    "name": "Indonesian", "addic7ed": True},
    "is":       {"code": 56,    "name": "Icelandic", "addic7ed": True},
    "it":       {"code": 7,     "name": "Italian", "addic7ed": True},
    "ja":       {"code": 32,    "name": "Japanese", "addic7ed": True},
    "ko":       {"code": 42,    "name": "Korean", "addic7ed": True},
    "lt":       {"code": 58,    "name": "Lithuanian", "addic7ed": True},
    "lv":       {"code": 57,    "name": "Latvian", "addic7ed": True},
    "mk":       {"code": 49,    "name": "Macedonian", "addic7ed": True},
    "ms":       {"code": 40,    "name": "Malay", "addic7ed": True},
    "nl":       {"code": 17,    "name": "Dutch", "addic7ed": True},
    "no":       {"code": 29,    "name": "Norwegian", "addic7ed": True},
    "pl":       {"code": 21,    "name": "Polish", "addic7ed": True},
    "pt":       {"code": 9,     "name": "Portuguese", "addic7ed": True},
    "pt-br":    {"code": 10,    "name": "Portuguese (Brazilian)", "addic7ed": True},
    "ro":       {"code": 26,    "name": "Romanian", "addic7ed": True},
    "ru":       {"code": 19,    "name": "Russian", "addic7ed": True},
    "si":       {"code": 60,    "name": "Sinhala", "addic7ed": True},
    "sk":       {"code": 25,    "name": "Slovak", "addic7ed": True},
    "sl":       {"code": 22,    "name": "Slovenian", "addic7ed": True},
    "sq":       {"code": 52,    "name": "Albanian", "addic7ed": True},
    "sr":       {"code": 39,    "name": "Serbian (Cyrillic)", "addic7ed": True},
    "sr-latn":  {"code": 39,    "name": "Serbian (Latin)", "addic7ed": True},
    "sv":       {"code": 18,    "name": "Swedish", "addic7ed": True},
    "ta":       {"code": 59,    "name": "Tamil", "addic7ed": True},
    "th":       {"code": 46,    "name": "Thai", "addic7ed": True},
    "tr":       {"code": 16,    "name": "Turkish", "addic7ed": True},
    "uk":       {"code": 51,    "name": "Ukrainian", "addic7ed": True},
    "vi":       {"code": 45,    "name": "Vietnamese", "addic7ed": True},
    "zh-hans":  {"code": 41,    "name": "Chinese (Simplified)", "addic7ed": True},
    "zh-hant":  {"code": 24,    "name": "Chinese (Traditional)", "addic7ed": True}
}
